#!/bin/bash

db_path="./dbs"
database_name="$1"

db_dir="$db_path/$database_name"

# Only real table files; ignore .metadata folder
# This loop checks each file in the directory and stores its name if it is a file
tables=$(for f in "$db_dir"/*; do [[ -f "$f" ]] && basename "$f"; done)

# Check if the database directory has any files (not empty)
if [ -z "$tables" ]; then
    echo "This database has no tables."
    exit
fi

echo "Available tables:"
echo $tables
read -p "Type the table you want to view: " tableName

chosen_tbl=""

until [[ -n "$chosen_tbl" ]]; do
  for t in $tables; do
    if [[ "$tableName" == "$t" ]]; then
      chosen_tbl="$t"
      break
    fi
  done
  if [[ -z "$chosen_tbl" ]]; then
    read -p "That table does not exist. Try another name: " tableName
  fi
done

tbl_path="$db_dir/$chosen_tbl"

echo "-----------------------------------------------"
echo "Contents of '$chosen_tbl':"
echo "-----------------------------------------------"


awk 'BEGIN {FS="|"; OFS="\t"} {
    for (i=1; i<=NF; i++) {
        printf "%-15s", $i
    }
    print ""
}' "$tbl_path"

echo "-----------------------------------------------"

./tableMenu "$database_name"